project:
  type: website

website:
  title: "IS415-G14"
  navbar:
    left: 
      - text: "Project Proposal"
        href: "Deliverables/Proposal.html"
      - text: "Project Poster"
        href: "Deliverables/Poster.html"
    right:
      - icon: github
        href: https://github.com/yozafard/IS415-G14
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

