```{r}
pacman::p_load(car, olsrr, corrplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary)
```

```{r}
mamikos_sf <- read_rds("data/mamikos_sf.rds")
mamikos_final <- read_rds("data/mamikos_final.rds")
bw <- read_rds("data/bw.rds")
gwr <- read_rds("data/gwr.rds")
```

```{r}
mamikos_final <- mamikos_final |>
  mutate(log_price = log(price_monthly))
mamikos_sp <- as_Spatial(mamikos_final)
```

```{r}
bw_type <- c('Adaptive')
# bw_type <- c('Fixed', 'Adaptive')
# calibration_method <- c("Cross-Validation")
# calibration_method <- c('Least Akaike Information Criterion')
calibration_method <- c("Cross-Validation", 'Least Akaike Information Criterion')
# dist_metric <- c("Euclidean")
dist_metric <- c('Manhattan')
# dist_metric <- c("Euclidean", 'Manhattan')
kernel <- c('Tricube', 'boxcar')
# kernel <- c("Gaussian", 'Exponential', 'Bisquare', 'Tricube', 'Boxcar')


formula <- log_price ~ gender + size + building_year + prox_airport + prox_gereja + prox_kantorpos + prox_kesehatan + prox_masjid + prox_stasiunka + prox_vihara + pendidikan_within_med + pura_within_med
```

```{r}
for (d in dist_metric) {
  print("Calculating distance matrix..")
  p <- ifelse(d == "Euclidean", 2, 1)
  distmat <- gw.dist(dp.locat = coordinates(mamikos_sp), longlat=TRUE, p=p)
  for (c in calibration_method) {
    for (b in bw_type) {
      for (k in kernel) {
        adaptive <- b == "Adaptive"
        approach <- ifelse(c == "Cross-Validation", "CV", "AIC")
        kern <- tolower(k)
        
        print(paste0("bw: ", b, ", calibration: ", c, ", dist: ", d, ", kernel: ", k))
        print("Calculating bandwidth...")
        bw <- bw.gwr(formula = formula, 
                     data=mamikos_sp, 
                     adaptive=adaptive,
                     approach=approach,
                     kernel=kern, 
                     p=p,
                     parallel.method = "omp",
                     dMat = distmat)
        
        fname_bw <- paste0("data/bw_", b, "_", c, "_", d, "_", k, ".rds")
        write_rds(bw, fname_bw)
        
        print(paste0("Calibrating GWR with bandwidth ", bw, "..."))
        gwr <- gwr.robust(formula = formula, 
                          data=mamikos_sp, 
                          adaptive=adaptive,
                          bw=bw, 
                          kernel=kern,
                          p=p,
                          parallel.method = "omp")
          
        fname_gwr <- paste0("data/gwr_", b, "_", c, "_", d, "_", k, ".rds")
        write_rds(gwr, fname_gwr)
        
        print("Done!")
      }
    }
  }
}
```

```{r}
d <- "Manhattan"
c <- "Cross-Validation"
b <- "Adaptive"
k <- "Boxcar"
# k <- "Tricube"

p <- ifelse(d == "Euclidean", 2, 1)
adaptive <- b == "Adaptive"
approach <- ifelse(c == "Cross-Validation", "CV", "AIC")
kern <- tolower(k)

print(paste0("bw: ", b, ", calibration: ", c, ", dist: ", d, ", kernel: ", k))
print("Calculating bandwidth...")
bw <- bw.gwr(formula = formula, 
             data=mamikos_sp, 
             adaptive=adaptive,
             approach=approach,
             kernel=kern, 
             p=p,
             longlat=T,
             parallel.method = "omp")

fname_bw <- paste0("data/bw_", b, "_", c, "_", d, "_", k, ".rds")
# write_rds(bw, fname_bw)

print(paste0("Calibrating GWR with bandwidth ", bw, "..."))
gwr <- gwr.robust(formula = formula, 
                  data=mamikos_sp, 
                  adaptive=adaptive,
                  bw=1736, 
                  kernel=kern,
                  p=p,
                  parallel.method = "omp")
  
fname_gwr <- paste0("data/gwr_", b, "_", c, "_", d, "_", k, ".rds")
# write_rds(gwr, fname_gwr)

print("Done!")
```

```{r}
gwr
```

## MLR

```{r}
mlr <- readRDS("data/mlr.rds")

mamikos_mlr <- mamikos_final |> 
  cbind(mlr$fitted.values) |> 
  cbind(mlr$residuals) |>
  rename(`residuals` = `mlr.residuals`, `fitted values` = `mlr.fitted.values`)

jakarta_mlr <-  jakarta_sf |>
  st_join(mamikos_mlr) |> 
  group_by(geometry, NAMOBJ) |> 
  summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)),
            .groups = "drop")

gwr <- read_rds(paste0(path, file))
gwr_sf <- gwr$SDF |> st_as_sf() |> st_transform(crs = 4326)
jakarta_gwr <- jakarta_sf |>
  st_join(gwr_sf) |> # Join data within the polygons
  group_by(geometry, NAMOBJ) |> # Group by some unique identifier for jakarta_sf polygons
  summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)),
            .groups = "drop")

fname <- paste0("data/jakarta_gwr/", substr(file, 5, nchar(file)))
write_rds(jakarta_gwr, fname)
```

## For Map

```{r}
jakarta_sf <- read_rds("data/jakarta_sf.rds")
path <- "data/model/"
files <- list.files(path=path)

for (file in files){
  gwr <- read_rds(paste0(path, file))
  gwr_sf <- gwr$SDF |> st_as_sf() |> st_transform(crs = 4326)
  jakarta_gwr <- jakarta_sf |>
    st_join(gwr_sf) |> # Join data within the polygons
    group_by(geometry, NAMOBJ) |> # Group by some unique identifier for jakarta_sf polygons
    summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)),
              .groups = "drop")
  
  fname <- paste0("data/jakarta_gwr/", substr(file, 5, nchar(file)))
  write_rds(jakarta_gwr, fname)
}
```

```{r}
write_rds(jakarta_gwr, "data/jakarta_gwr.rds")
```

```{r}
mamikos_palette <- colorRampPalette(c("#f95516", "#dbdbdb", "#2caa4a"))(100)

tmap_mode("view")
tm_shape(jakarta_gwr) +  # Your spatial polygons data
  tm_polygons(col="size",  # The variable to color by
              style="quantile",  # The method for creating color breaks
              palette=mamikos_palette,  # Your chosen color palette
              title="Local R2") +  # Legend title
  tm_view(set.zoom.limits = c(11,14))  # Set zoom limits

tmap_mode("plot")
```

```{r}
pacman::p_load(sf, tmap, dplyr, DT)
english_translations <- c("Gender", "Size", "Year of Construction", 
                          "Proximity to Airport", "Proximity to Church", 
                          "Proximity to Post Office", "Proximity to Health Facilities",
                          "Proximity to Mosque", "Proximity to Railway Station", 
                          "Proximity to Vihara", "Education Facilities within Range", 
                          "Pura within Range")
mlrd <- readRDS("data/mlr.rds")
datatable(mlrd$coefficients |> as.data.frame(),
          colnames = c("Variable", "Coefficient"),
          rownames = c("Intercept", english_translations))


mamikos_mlr <- read_rds("data/mamikos_final.rds") |> 
  mutate(`fitted values` = mlrd$fitted.values, 
         `residuals` = mlrd$residuals,
         `actual values` = mlrd$model$price_monthly)

jakarta_mlr <-  readRDS("data/jakarta_sf.rds") |>
  st_join(mamikos_mlr) |> 
  group_by(geometry, NAMOBJ) |> 
  summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)),
            .groups = "drop")

mamikos_palette <- colorRampPalette(c("#f95516", "#dbdbdb", "#2caa4a"))(100)

coef_choices <- c("gender", "size", "building_year", "prox_airport", 
                  "prox_gereja", "prox_kantorpos", "prox_kesehatan", 
                  "prox_masjid", "prox_stasiunka", "prox_vihara", 
                  "pendidikan_within_med", "pura_within_med")

english_translations <- c("Gender", "Size", "Year of Construction", 
                          "Proximity to Airport", "Proximity to Church", 
                          "Proximity to Post Office", "Proximity to Health Facilities",
                          "Proximity to Mosque", "Proximity to Railway Station", 
                          "Proximity to Vihara", "Education Facilities within Range", 
                          "Pura within Range")

names(coef_choices) <- english_translations

# Server logic for GWR
output = c()
output$GWRPlot <- renderTmap({
  plotted_coefficient <- coef_choices[input$gwr_coef]
  print(plotted_coefficient)
  
  bw <- input$bw
  bwc <- input$bwc
  dist <- input$dist
  kernel <- input$gwr_kernel
  
  # Load the processed GWR model
  fname <- paste0("gwr/data/jakarta_gwr/", bw, "_", bwc, "_", dist, "_", kernel, ".rds")
  jakarta_gwr <- readRDS(fname)
  
  # Use the reverse palette for the standard error
  paletteToUse <- if(plotted_coefficient == "size_SE") rev(mamikos_palette) else mamikos_palette
  
  tmap_mode("view")
  map <- tm_shape(jakarta_gwr) +
    tm_fill(col=plotted_coefficient,
            style="quantile",
            palette=paletteToUse,
            title=input$gwr_coef,
            midpoint = 0,
            popup.vars=c(plotted_coefficient)) +
    tm_borders() +
    tm_view(set.zoom.limits = c(11,14))  # Set zoom limits
  map
})

output$MLRDPlot <- renderTmap({
  
  plotted_coefficient <- input$mlr_coef
  # Use the reverse palette for the standard error
  paletteToUse <- if(plotted_coefficient == "size_SE") rev(mamikos_palette) else mamikos_palette
  
  tmap_mode("view")
  map <- tm_shape(jakarta_mlr) +
    tm_fill(col=input$mlr_coef,
            style="quantile",
            palette=paletteToUse,
            title=input$mlr_coef,
            midpoint = 0,
            popup.vars=c(plotted_coefficient)) +
    tm_borders() +
    tm_view(set.zoom.limits = c(11,14))  # Set zoom limits
  map
})
```
